server:
  port: 8080

spring:
  application:
    name: rbac-system
  
  datasource:
    url: jdbc:h2:mem:rbac_db;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    username: sa
    password: 
    driver-class-name: org.h2.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.H2Dialect
  
  h2:
    console:
      enabled: true
      path: /h2-console

logging:
  level:
    com.example.rbac: debug
